cluster: "pnx.cd.pnx.com.au"

channel: '#site1'

package:
  steps:
    - "composer install --no-dev --prefer-dist --no-progress --optimize-autoloader"
    - "npm install --loglevel silent &> /tmp/npminstall.log"
    - "node_modules/.bin/gulp build"

deploySteps:
  - make deploy

# A list of all environment configuration.
environments:
  - name: "dev"
    spec:
      domain:
        - "site1-qa.cd.pnx.com.au"
      healthCheck:
        path: /healthz/d8.php
      mounts: *mounts
      crons:  *crons
  - name: "staging"
    spec:
      domain:
        - "site1-staging.cd.pnx.com.au"
      healthCheck:
        path: /healthz/d8.php
      mounts: *mounts
      crons:  *crons
  - name: "prod"
    spec:
      domain:
        - "site1-prod.cd.pnx.com.au"
      healthCheck:
        path: /healthz/d8.php
      minInstances: 2
      maxMemory:    512
      mounts:       *mounts
      crons:        *crons

# Standard mount configuration for all environments.
mounts: &mounts
  - name: "public"
    path: "/data/app/sites/default/files"
  - name: "private"
    path: "/private"

# Standard cron runs for all environments.
crons: &crons
  - name:       "drush"
    workingDir: "/data/app"
    seconds:    3600
    command:    "drush cron"
