<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: articles.proto

namespace Articles;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>articles.Article</code>
 */
class Article extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>string title = 1;</code>
     */
    private $title = '';
    /**
     * <code>string body = 2;</code>
     */
    private $body = '';

    public function __construct() {
        \GPBMetadata\Articles::initOnce();
        parent::__construct();
    }

    /**
     * <code>string title = 1;</code>
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * <code>string title = 1;</code>
     */
    public function setTitle($var)
    {
        GPBUtil::checkString($var, True);
        $this->title = $var;
    }

    /**
     * <code>string body = 2;</code>
     */
    public function getBody()
    {
        return $this->body;
    }

    /**
     * <code>string body = 2;</code>
     */
    public function setBody($var)
    {
        GPBUtil::checkString($var, True);
        $this->body = $var;
    }

}

